# Домашнее задание "Продвинутая линейная алгебра".

### Уровень 0:

Придумайте матрицы, которые обладают следующими свойствами:
(P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!)

a) Диагональная, ортогональная, но не единичная(!)

In [1]:
import numpy as np
import math

In [2]:
m1 = np.diag([math.sin(math.pi/2), -math.sin(math.pi/2), math.cos(0)])
m1 @ m1.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

b) Верхнетреугольная, ортогональная

In [3]:
m2 = np.triu([[-1, 0, 0],[0, -1, 0],[0, 0, -1]])
m2 @ m2.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

c) Нижнетреугольная, ортогональная

In [4]:
m3 = np.tril([[1, 0, 0],[0, 1, 0],[0, 0, 1]])
m3 @ m3.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

d) Матрица, у которой определитель = 1, и все элементы не равны 0

In [5]:
m4 = np.array([[2,3],[3,5]])
round(np.linalg.det(m4))

1.0

Найдите собственные значения и собственные вектора матриц:

In [7]:
m5 = np.array([[2, 2],
              [1, 3]])
w,v = np.linalg.eig(m5)
print('Собственные значения:', w[0], 'и', w[1], '\nСобственные вектора:', v[0], 'и', v[1])

Собственные значения: 1.0 и 4.0 
Собственные вектора: [-0.89442719 -0.70710678] и [ 0.4472136  -0.70710678]


### Уровень 1:

Найдите спектральное разложение матрицы:

In [8]:
m = np.array([[1, 2],
              [2,3]])

U, D, V = np.linalg.svd(m)
M = U @ np.diag(D) @ V
print(M)

[[1. 2.]
 [2. 3.]]


Постройте зависимость качества восстановления рукописных цифр (MNIST) в зависимости от различного количества компонент PCA. В качестве метрики различия предлагаю использовать MSE.*




У PCA есть метод transform и inverse_transofrm. Первый - снижает размерность, второй - восстанавливает оригинальные данные с потерей информации.
Надо посчитать насколько в среднем точно восстанавливается оригинальная картинка в зависимости от количества компонент в PCA.